#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <binreader.h>
#include <error_handler.h>

/* Global variables, a necessary evil. */
unsigned int n_encodings = 0,
             first_enc = 0, 
             sec_enc = 0,
             third_enc = 0;

/* The data divided in channels. */
uint32_t **data_vector = NULL;

bitbuffer *data_buffer = NULL,
          *output_buffer = NULL;

/* The header of the file being encoded. */
binheader *input_file_header;

/* The frequencies vector, generated by the Huffman encoding.  */
uint64_t **frequencies;

/* Specific parameters of each encoding. One value per channel. */
uint32_t *nbits_run = NULL,
         *firsts = NULL,
         *max_bits = NULL,
         *nbits_code = NULL,
         frequency_length;

void dec_prepare_input_file(FILE *fp)
{
    input_file_header = malloc(sizeof(binheader));
    binh_get_header(input_file_header, fp, &frequencies, &frequency_length, &firsts, &max_bits, &nbits_run, &nbits_code);
    first_enc = input_file_header->firstEncoding;
    sec_enc = input_file_header->secondEncoding;
    third_enc = input_file_header->thirdEncoding;
}


void dec_prepare_output_file (FILE *fp)
{
    free(input_file_header);
}

void dec_huffman(int previous, FILE *in_fp)
{
        printf("Applying Huffman decoding...\n");

        switch (previous) {
                case (-1):
                        {
                        }
                        break;

                case RUN_LENGTH:
                        {
                        }
                        break;

                case DELTA:
                        {
                        }
                        break;
        }
}

void dec_run_length(int previous, FILE *in_fp)
{
    printf("Applying run-length decoding...\n");

    switch (previous) {
            case -1:
                    {
                    }
                    break;

            case HUFFMAN:
                    {
                            ERROR("Corrupted file.")
                            exit(1);
                    }
                    break;

            case DELTA:
                    {

                    }
                    break;
    }
}

void dec_delta(int previous, FILE *in_fp)
{

        printf("Delta decoding...\n");
        switch (previous) {
            case -1:
                    {
                    }
                    break;

            case RUN_LENGTH:
                    {
                    
                    }
                    break;

            case HUFFMAN:
                    {
                            ERROR("Corrupted file.")
                            exit(1);
                    }
                    break;
        }
}

int main(int argc, char *argv[])
{
    FILE *in_fp, *out_fp;

        
    if((in_fp = fopen(argv[1], "rb"))==NULL){
        IO_OPEN_ERROR;
        return 1;
    }
    
    if((out_fp = fopen(argv[2], "wb+"))==NULL){
        IO_OPEN_ERROR;
        return 1;
    }

    printf("Starting decoding process...\n");

    dec_prepare_input_file(in_fp);

    switch (input_file_header.firstEncoding){
            case HUFFMAN:
                    dec_huffman();
                    break;
            case RUN_LENGTH:
                    dec_length();
                    break;
            case DELTA: 
                    dec_delta();
    }

    switch(input_file_header.secondEncoding){
            case HUFFMAN:
                    dec_huffman();
                    break;
            case RUN_LENGTH:
                    dec_length();
                    break;
            case DELTA: 
                    dec_delta();
            
    }

    switch(input_file_header.thirdEncoding){
            case HUFFMAN:
                    dec_huffman();
                    break;
            case RUN_LENGTH:
                    dec_length();
                    break;
            case DELTA: 
                    dec_delta();
            
    }

    enc_prepare_output_file(out_fp);

    fclose(in_fp);
    fclose(out_fp);
    return 0;
}
